### ISSUE TITLE
Help: Gateway timeout

### ISSUE THREAD

**Issue by veitbjarsch** [logchimp/logchimp#825]
Hi, 
I just installed logchimp on my server. The frontend is working fine, but when it tries to access the API (e.g. setup) it runs always in a gateway timeout. How can I receive more information what is going wrong?

Best Regards
Veit

**Comment by rihards-simanovics** [comment]
Hey just started working with this project myself, when exactly do you experience this? is it during the access to DB, I found that if I try to enter a title that's too large (i.e. larger than 15 char) instead of gracefully failing it just returns 504 Gateway timeout. Perhaps you ought to check your DB connection if you get this during the setup phase?

**Comment by rihards-simanovics** [comment]
@mittalyashu would you like a hand with the project, I need/like this project and am happy to put in some work, I can see the Vue theme hasn't been maintained much for the past couple of years (and only supports node16<=).

I mostly do frontend but can give a hand with backend as well.

**Comment by mittalyashu** [comment]
Hey @rihards-simanovics 

Really appreciate your interest in contributing to this project. PRs are always welcome to improve the project. 🙂

As for the Vue theme, it has been moved to this repository under the `packages` directory.

**Comment by mittalyashu** [comment]
I have created a patch to return a `500` status error code when there is something issue on the backend.

Don't hesitate to re-open the issue if you facing this issue again.
